"""add_indexes_to_streak

Revision ID: 099d0d412525
Revises: 4f63ef3824ae
Create Date: 2025-04-30 09:22:40.299481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '099d0d412525'
down_revision: Union[str, None] = '4f63ef3824ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('streaks', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index('ix_streaks_game_range', 'streaks', ['start_game_id', 'end_game_id'], unique=False)
    op.create_index(op.f('ix_streaks_streak_number'), 'streaks', ['streak_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_streaks_streak_number'), table_name='streaks')
    op.drop_index('ix_streaks_game_range', table_name='streaks')
    op.drop_column('streaks', 'updated_at')
    # ### end Alembic commands ### 