"""Update Game model to match DB schema

Revision ID: 82a2d4d739ec
Revises: 7ffffb4c5280
Create Date: 2025-04-30 05:00:12.311752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82a2d4d739ec'
down_revision: Union[str, None] = '7ffffb4c5280'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 