"""Remove streak_length_error and prediction_type columns

Revision ID: 9fd26749551a
Revises: dc5f94f49c90
Create Date: 2025-04-30 11:26:41.839336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fd26749551a'
down_revision: Union[str, None] = 'dc5f94f49c90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('streak_predictions', 'prediction_type')
    op.drop_column('streak_predictions', 'streak_length_error')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('streak_predictions', sa.Column('streak_length_error', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('streak_predictions', sa.Column('prediction_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ### 