"""add_enhanced_analytics_fields_to_predictions

Revision ID: cfe65930d537
Revises: 01b0856cb3c9
Create Date: 2025-04-30 10:55:42.937066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfe65930d537'
down_revision: Union[str, None] = '01b0856cb3c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('streak_predictions', sa.Column('streak_length_error', sa.Integer(), nullable=True))
    op.add_column('streak_predictions', sa.Column('prediction_type', sa.String(), nullable=True))
    op.add_column('streak_predictions', sa.Column('confidence_distribution', sa.JSON(), nullable=True))
    op.add_column('streak_predictions', sa.Column('prediction_entropy', sa.Float(), nullable=True))
    op.add_column('streak_predictions', sa.Column('time_to_verification', sa.Integer(), nullable=True))
    op.add_column('streak_predictions', sa.Column('day_of_week', sa.Integer(), nullable=True))
    op.add_column('streak_predictions', sa.Column('model_version', sa.String(), nullable=True))
    op.add_column('streak_predictions', sa.Column('feature_set', sa.String(), nullable=True))
    op.add_column('streak_predictions', sa.Column('lookback_window', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('streak_predictions', 'lookback_window')
    op.drop_column('streak_predictions', 'feature_set')
    op.drop_column('streak_predictions', 'model_version')
    op.drop_column('streak_predictions', 'day_of_week')
    op.drop_column('streak_predictions', 'time_to_verification')
    op.drop_column('streak_predictions', 'prediction_entropy')
    op.drop_column('streak_predictions', 'confidence_distribution')
    op.drop_column('streak_predictions', 'prediction_type')
    op.drop_column('streak_predictions', 'streak_length_error')
    # ### end Alembic commands ### 